name: dnext_chatbot
description: "DNext ChatBot"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  openid_client: ^0.4.8
  file_picker: ^8.1.2
  cached_network_image: ^3.4.1
  shared_preferences:
  flutter_secure_storage:
  logger:
  dio:
  image_picker:
  flutter_spinkit:
  url_launcher:
  adaptive_theme:
  get:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true