
services:
  keycloak:
    build: .
    image: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
      - 19080:9080
      - 19443:9443
      - 10990:10990
    command: "start-dev --import-realm"